version: '3'
services:
  test:
    build: ../
    image: nanamo/6_php_ezunser
    environment:
      # 仅为测试用flag
      FLAG: "flag{a63b4d37-7681-4850-b6a7-0d7109febb19}"
    ports:
      # 设置了暴露端口
      - 8081:80
    restart: unless-stopped
